export const GENRE_LIST = [
  "Adult",
  "Adult Fantasy",
  "Adventure",
  "African",
  "AI",
  "Alien",
  "Anthology",
  "Antihero",
  "Asian",
  "Asian Author",
  "Biography",
  "Black Author",
  "Brasil",
  "Cats",
  "Chick Lit",
  "China",
  "Classic",
  "Coding",
  "Comedy",
  "Comic",
  "Coming of Age",
  "Contemporary",
  "Cozy",
  "Cozy Mystery",
  "Crime",
  "Dark Academia",
  "Detective",
  "Depression",
  "Disability",
  "Dragons",
  "Drama",
  "Dystopia",
  "Enemies to Lovers",
  "Epic",
  "Epic Fantasy",
  "Essays",
  "Fantasy",
  "Fairytale",
  "Feminism",
  "Fiction",
  "Found Family",
  "Friendship",
  "Fundamentals",
  "Ghosts",
  "Gothic",
  "Graphic Novel",
  "Greek",
  "Heist",
  "Historical Books",
  "Historical Fiction",
  "History",
  "Horror",
  "Humor",
  "Immigrants",
  "Inheritance",
  "Iran",
  "Letters",
  "Literary",
  "Literatura Brasileira",
  "Magic",
  "Magical Realism",
  "Marriage",
  "Medicine",
  "Memoir",
  "Mental Health",
  "Middle Grade",
  "Murder Mystery",
  "Mystery",
  "Mythology",
  "Nature",
  "New Adult",
  "Noir",
  "Non Fiction",
  "Novella",
  "Occult",
  "Personality",
  "Pessimist",
  "Philosophy",
  "Pirates",
  "Poetry",
  "Post Apocalyptic",
  "Queer",
  "Race",
  "Retelling",
  "Robots",
  "Romance",
  "Satire",
  "Science",
  "Science Fiction",
  "Short Story",
  "Slavery",
  "Slice of Life",
  "Small Town",
  "Space",
  "Spy? Sorta?",
  "Superhero",
  "Supernatural",
  "Suspense",
  "Teen",
  "Thriller",
  "Time Travel",
  "Unique",
  "Urban Fantasy",
  "Vampire",
  "Video Games",
  "War",
  "Witches",
  "Young Adult",
] as const;

export type Genre = (typeof GENRE_LIST)[number];
